sudo: false
language: node_js
os: linux

cache:
  directories:
    - "node_modules"

before_install:
  - '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest' # skipped when using node 9
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

script:
  - npm run lint
  - npm run build
    
deploy:
  - provider: script
    script: chmod +x scripts/deploy.sh && scripts/deploy.sh
    skip_cleanup: true
    on:
      tags: true
