defaults: &defaults
  working_directory: /tmp/usina-dos-bags
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-
      
      - run:
          name: Setup greekeeper-lockfile-update
          command: |
            yarn global add greenkeeper-lockfile@1

      - run:
          name: Download dependencies (yarn)
          command: |
            greenkeeper-lockfile-update
            yarn
            greenkeeper-lockfile-upload

      - save_cache:
          key: v3-dependencies-{{ checksum "package.json" }}
          paths:
            - /tmp/usina-dos-bags/node_modules

      - run: yarn lint
      - run: yarn build

      - persist_to_workspace:
          root: /tmp/usina-dos-bags
          paths:
            - build

  deploy:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/usina-dos-bags

      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "package.json" }}
            - v3-dependencies-

      - run:
          name: Deploy Master to Firebase
          command: yarn deploy

workflows:
  version: 2
  
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
