defaults: &defaults
  working_directory: /tmp/usina-dos-bags
  docker:
    - image: circleci/node:8

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - /tmp/usina-dos-bags/node_modules

      - run: npm run lint
      - run: npm run build
      - persist_to_workspace:
          root: /tmp/usina-dos-bags
          paths:
            - build

  deploy:
    <<: *defaults
    steps:
      - checkout

      - attach_workspace:
          at: /tmp/usina-dos-bags

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Deploy Master to Firebase
          command: npm run deploy

workflows:
  version: 2
  
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
